### ISSUE TITLE
How to set up NSM on startup on Linux?

### ISSUE THREAD

**Issue by sriharikapu** [seanohollaren/nsolid-manager#25]
How to setup NSM on startup on Linux, Debian & Ubuntu?
How to list all the ports that are currently active on NSM?

Can someone provide me details on the above questions?

**Comment by seanohollaren** [comment]
NSM has been broken by more recent versions of nsolid and this project is no longer supported.  I'd instead install regular nsolid and refer to the NodeSource docs.

**Comment by sriharikapu** [comment]
Thank you so much @seanohollaren
