### ISSUE TITLE
N|Solid proxy looks for .nsolid-proxyrc file in pwd

### ISSUE THREAD

**Issue by seanohollaren** [seanohollaren/nsolid-manager#6]
Currently the nsolid proxy will look for the .nsolid-proxyrc configuration file in the folder of the current execution context instead of its own folder, which means it currently breaks if the manager is invoked from anywhere other than the root of the nsolid-manager folder.

Need to specify where the proxy should look for its config file so it doesn't matter which directory it's called from.

**Comment by seanohollaren** [comment]
Looking through the docs, I'm not sure if I see a way to override the behavior of looking in the current directory for the config file.  Short of modifying the nsolid code.

**Comment by seanohollaren** [comment]
Per @awolden, we found the proxy is coded to look in the current directory for the file.  

Easiest fix for this would be for the proxy to change to resolve the path of the directory it lives in and reference the config file that way.

Any fix on our end will probably be hacky.

**Comment by seanohollaren** [comment]
Their tweet: https://twitter.com/NodeSource/status/710525350208405504

Their SO tag: http://stackoverflow.com/questions/tagged/nsolid

**Comment by awolden** [comment]
I created a SO post here: http://stackoverflow.com/questions/36073741/unable-to-specify-nsolid-proxyrc-for-nsolid-proxy-is-causing-issues

**Comment by seanohollaren** [comment]
Cool, they gave us the solution.

http://stackoverflow.com/a/36074237/144121

You can pass the explicit location of the config file with the --config flag:

`nsolid proxy.js --config /path/to/config/file`

**Comment by seanohollaren** [comment]
PR is in: #10
